GET http://localhost:5000 HTTP/1.1

### Register user
POST http://localhost:5000/register HTTP/1.1
content-type: application/json

{
    "email": "percymudzinganyama@gmail.com",
    "password": "persla",
    "confirmation": "persla",
    "firstName": "Perseverance",
    "lastName": "Mudzinganyama"
}

### Login Route
POST http://localhost:5000/login HTTP/1.1
content-type: application/json

{
    "email": "percymudzinga@gmail.com",
    "password": "persla2006"
}
