version: '3'
services: 
  app:
    container_name: yadahdash
    restart: always
    build: .
    links: 
      - yadahdashdb
    volumes: 
      - store:/usr/src/app/public/uploads
      - node_modules:/usr/src/app/node_modules
    networks:
      - net
    ports: 
      - '81:5000'
    environment: 
      - DB_PATH=yadahdashdb
  yadahdashdb:
    container_name: yadahdashdb
    image: mongo
    volumes: 
      - db:/data/db
    networks: 
      - net
    ports:
      - '27017'
networks: 
  net:
    driver: bridge
volumes: 
  db:
  store:
  node_modules: